SET(INPUT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/definitions)
FILE(GLOB PROTO_INPUT ${CMAKE_CURRENT_SOURCE_DIR}/definitions/*.proto)
FIND_PROGRAM(PROTOC protoc)
SET(PROTOC_C_OUT_FLAG --cpp_out)
set(PROTO_GEN_DIR ${CMAKE_CURRENT_SOURCE_DIR}/gen)

FOREACH(PROTO_FILE ${PROTO_INPUT})
GET_FILENAME_COMPONENT(PROTO_NAME ${PROTO_FILE} NAME_WE)
SET(CUR_PROTO_GEN
${PROTO_GEN_DIR}/${PROTO_NAME}.pb.h
${PROTO_GEN_DIR}/${PROTO_NAME}.http://pb.cc
)
SET(PROTO_GEN
${PROTO_GEN}
${CUR_PROTO_GEN}
)
ADD_CUSTOM_COMMAND(
OUTPUT ${CUR_PROTO_GEN}
COMMAND ${PROTOC} ${PROTO_FILE} ${PROTOC_C_OUT_FLAG} ${PROTO_GEN_DIR} -I${INPUT_DIR}
DEPENDS ${PROTOC} ${PROTO_FILE}
WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
)
endforeach(PROTO_FILE ${PROTO_INPUT})

ADD_LIBRARY(sample STATIC
OtherFiles.cpp
OtherFiles.h
${PROTO_GEN}
)
SET_SOURCE_FILES_PROPERTIES(
${PROTO_GEN}
PROPERTIES
GENERATED TRUE)
TARGET_LINK_LIBRARIES(sample protobuf)