// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CardSellConfig.proto

#ifndef PROTOBUF_CardSellConfig_2eproto__INCLUDED
#define PROTOBUF_CardSellConfig_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "ConfigTypeGroup.pb.h"
// @@protoc_insertion_point(includes)

namespace DianShiTech {
namespace Config {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_CardSellConfig_2eproto();
void protobuf_AssignDesc_CardSellConfig_2eproto();
void protobuf_ShutdownFile_CardSellConfig_2eproto();

class CardSellConfig;

// ===================================================================

class CardSellConfig : public ::google::protobuf::Message {
 public:
  CardSellConfig();
  virtual ~CardSellConfig();

  CardSellConfig(const CardSellConfig& from);

  inline CardSellConfig& operator=(const CardSellConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CardSellConfig& default_instance();

  void Swap(CardSellConfig* other);

  // implements Message ----------------------------------------------

  CardSellConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CardSellConfig& from);
  void MergeFrom(const CardSellConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 currency_type = 5;
  inline bool has_currency_type() const;
  inline void clear_currency_type();
  static const int kCurrencyTypeFieldNumber = 5;
  inline ::google::protobuf::int32 currency_type() const;
  inline void set_currency_type(::google::protobuf::int32 value);

  // optional int32 price = 6;
  inline bool has_price() const;
  inline void clear_price();
  static const int kPriceFieldNumber = 6;
  inline ::google::protobuf::int32 price() const;
  inline void set_price(::google::protobuf::int32 value);

  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // optional int32 level = 4;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 4;
  inline ::google::protobuf::int32 level() const;
  inline void set_level(::google::protobuf::int32 value);

  // optional int32 card_max_rank = 3;
  inline bool has_card_max_rank() const;
  inline void clear_card_max_rank();
  static const int kCardMaxRankFieldNumber = 3;
  inline ::google::protobuf::int32 card_max_rank() const;
  inline void set_card_max_rank(::google::protobuf::int32 value);

  // optional int32 rank = 2;
  inline bool has_rank() const;
  inline void clear_rank();
  static const int kRankFieldNumber = 2;
  inline ::google::protobuf::int32 rank() const;
  inline void set_rank(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:DianShiTech.Config.CardSellConfig)
 private:
  inline void set_has_currency_type();
  inline void clear_has_currency_type();
  inline void set_has_price();
  inline void clear_has_price();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_card_max_rank();
  inline void clear_has_card_max_rank();
  inline void set_has_rank();
  inline void clear_has_rank();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 currency_type_;
  ::google::protobuf::int32 price_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 level_;
  ::google::protobuf::int32 card_max_rank_;
  ::google::protobuf::int32 rank_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_CardSellConfig_2eproto();
  friend void protobuf_AssignDesc_CardSellConfig_2eproto();
  friend void protobuf_ShutdownFile_CardSellConfig_2eproto();

  void InitAsDefaultInstance();
  static CardSellConfig* default_instance_;
};
// ===================================================================


// ===================================================================

// CardSellConfig

// optional int32 currency_type = 5;
inline bool CardSellConfig::has_currency_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CardSellConfig::set_has_currency_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CardSellConfig::clear_has_currency_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CardSellConfig::clear_currency_type() {
  currency_type_ = 0;
  clear_has_currency_type();
}
inline ::google::protobuf::int32 CardSellConfig::currency_type() const {
  return currency_type_;
}
inline void CardSellConfig::set_currency_type(::google::protobuf::int32 value) {
  set_has_currency_type();
  currency_type_ = value;
}

// optional int32 price = 6;
inline bool CardSellConfig::has_price() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CardSellConfig::set_has_price() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CardSellConfig::clear_has_price() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CardSellConfig::clear_price() {
  price_ = 0;
  clear_has_price();
}
inline ::google::protobuf::int32 CardSellConfig::price() const {
  return price_;
}
inline void CardSellConfig::set_price(::google::protobuf::int32 value) {
  set_has_price();
  price_ = value;
}

// optional int32 id = 1;
inline bool CardSellConfig::has_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CardSellConfig::set_has_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CardSellConfig::clear_has_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CardSellConfig::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 CardSellConfig::id() const {
  return id_;
}
inline void CardSellConfig::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// optional int32 level = 4;
inline bool CardSellConfig::has_level() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CardSellConfig::set_has_level() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CardSellConfig::clear_has_level() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CardSellConfig::clear_level() {
  level_ = 0;
  clear_has_level();
}
inline ::google::protobuf::int32 CardSellConfig::level() const {
  return level_;
}
inline void CardSellConfig::set_level(::google::protobuf::int32 value) {
  set_has_level();
  level_ = value;
}

// optional int32 card_max_rank = 3;
inline bool CardSellConfig::has_card_max_rank() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CardSellConfig::set_has_card_max_rank() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CardSellConfig::clear_has_card_max_rank() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CardSellConfig::clear_card_max_rank() {
  card_max_rank_ = 0;
  clear_has_card_max_rank();
}
inline ::google::protobuf::int32 CardSellConfig::card_max_rank() const {
  return card_max_rank_;
}
inline void CardSellConfig::set_card_max_rank(::google::protobuf::int32 value) {
  set_has_card_max_rank();
  card_max_rank_ = value;
}

// optional int32 rank = 2;
inline bool CardSellConfig::has_rank() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CardSellConfig::set_has_rank() {
  _has_bits_[0] |= 0x00000020u;
}
inline void CardSellConfig::clear_has_rank() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void CardSellConfig::clear_rank() {
  rank_ = 0;
  clear_has_rank();
}
inline ::google::protobuf::int32 CardSellConfig::rank() const {
  return rank_;
}
inline void CardSellConfig::set_rank(::google::protobuf::int32 value) {
  set_has_rank();
  rank_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Config
}  // namespace DianShiTech

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CardSellConfig_2eproto__INCLUDED
