// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CombineSkillEffectConfig.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CombineSkillEffectConfig.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace DianShiTech {
namespace Config {

namespace {

const ::google::protobuf::Descriptor* CombineSkillEffectConfig_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CombineSkillEffectConfig_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CombineSkillEffectConfig_2eproto() {
  protobuf_AddDesc_CombineSkillEffectConfig_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CombineSkillEffectConfig.proto");
  GOOGLE_CHECK(file != NULL);
  CombineSkillEffectConfig_descriptor_ = file->message_type(0);
  static const int CombineSkillEffectConfig_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CombineSkillEffectConfig, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CombineSkillEffectConfig, img_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CombineSkillEffectConfig, words_),
  };
  CombineSkillEffectConfig_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CombineSkillEffectConfig_descriptor_,
      CombineSkillEffectConfig::default_instance_,
      CombineSkillEffectConfig_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CombineSkillEffectConfig, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CombineSkillEffectConfig, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CombineSkillEffectConfig));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CombineSkillEffectConfig_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CombineSkillEffectConfig_descriptor_, &CombineSkillEffectConfig::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CombineSkillEffectConfig_2eproto() {
  delete CombineSkillEffectConfig::default_instance_;
  delete CombineSkillEffectConfig_reflection_;
}

void protobuf_AddDesc_CombineSkillEffectConfig_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::DianShiTech::Config::protobuf_AddDesc_ConfigTypeGroup_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\036CombineSkillEffectConfig.proto\022\022DianSh"
    "iTech.Config\032\025ConfigTypeGroup.proto\"B\n\030C"
    "ombineSkillEffectConfig\022\n\n\002id\030\001 \001(\005\022\013\n\003i"
    "mg\030\002 \001(\005\022\r\n\005words\030\003 \001(\005", 143);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CombineSkillEffectConfig.proto", &protobuf_RegisterTypes);
  CombineSkillEffectConfig::default_instance_ = new CombineSkillEffectConfig();
  CombineSkillEffectConfig::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CombineSkillEffectConfig_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CombineSkillEffectConfig_2eproto {
  StaticDescriptorInitializer_CombineSkillEffectConfig_2eproto() {
    protobuf_AddDesc_CombineSkillEffectConfig_2eproto();
  }
} static_descriptor_initializer_CombineSkillEffectConfig_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CombineSkillEffectConfig::kIdFieldNumber;
const int CombineSkillEffectConfig::kImgFieldNumber;
const int CombineSkillEffectConfig::kWordsFieldNumber;
#endif  // !_MSC_VER

CombineSkillEffectConfig::CombineSkillEffectConfig()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CombineSkillEffectConfig::InitAsDefaultInstance() {
}

CombineSkillEffectConfig::CombineSkillEffectConfig(const CombineSkillEffectConfig& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CombineSkillEffectConfig::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0;
  img_ = 0;
  words_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CombineSkillEffectConfig::~CombineSkillEffectConfig() {
  SharedDtor();
}

void CombineSkillEffectConfig::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CombineSkillEffectConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CombineSkillEffectConfig::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CombineSkillEffectConfig_descriptor_;
}

const CombineSkillEffectConfig& CombineSkillEffectConfig::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CombineSkillEffectConfig_2eproto();
  return *default_instance_;
}

CombineSkillEffectConfig* CombineSkillEffectConfig::default_instance_ = NULL;

CombineSkillEffectConfig* CombineSkillEffectConfig::New() const {
  return new CombineSkillEffectConfig;
}

void CombineSkillEffectConfig::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = 0;
    img_ = 0;
    words_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CombineSkillEffectConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_img;
        break;
      }

      // optional int32 img = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_img:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &img_)));
          set_has_img();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_words;
        break;
      }

      // optional int32 words = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_words:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &words_)));
          set_has_words();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CombineSkillEffectConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // optional int32 img = 2;
  if (has_img()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->img(), output);
  }

  // optional int32 words = 3;
  if (has_words()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->words(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CombineSkillEffectConfig::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // optional int32 img = 2;
  if (has_img()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->img(), target);
  }

  // optional int32 words = 3;
  if (has_words()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->words(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CombineSkillEffectConfig::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // optional int32 img = 2;
    if (has_img()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->img());
    }

    // optional int32 words = 3;
    if (has_words()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->words());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CombineSkillEffectConfig::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CombineSkillEffectConfig* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CombineSkillEffectConfig*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CombineSkillEffectConfig::MergeFrom(const CombineSkillEffectConfig& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_img()) {
      set_img(from.img());
    }
    if (from.has_words()) {
      set_words(from.words());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CombineSkillEffectConfig::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CombineSkillEffectConfig::CopyFrom(const CombineSkillEffectConfig& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CombineSkillEffectConfig::IsInitialized() const {

  return true;
}

void CombineSkillEffectConfig::Swap(CombineSkillEffectConfig* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(img_, other->img_);
    std::swap(words_, other->words_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CombineSkillEffectConfig::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CombineSkillEffectConfig_descriptor_;
  metadata.reflection = CombineSkillEffectConfig_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Config
}  // namespace DianShiTech

// @@protoc_insertion_point(global_scope)
