// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DailyTaskInitDataConfig.proto

#ifndef PROTOBUF_DailyTaskInitDataConfig_2eproto__INCLUDED
#define PROTOBUF_DailyTaskInitDataConfig_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "ConfigTypeGroup.pb.h"
// @@protoc_insertion_point(includes)

namespace DianShiTech {
namespace Config {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_DailyTaskInitDataConfig_2eproto();
void protobuf_AssignDesc_DailyTaskInitDataConfig_2eproto();
void protobuf_ShutdownFile_DailyTaskInitDataConfig_2eproto();

class DailyTaskInitDataConfig;

// ===================================================================

class DailyTaskInitDataConfig : public ::google::protobuf::Message {
 public:
  DailyTaskInitDataConfig();
  virtual ~DailyTaskInitDataConfig();

  DailyTaskInitDataConfig(const DailyTaskInitDataConfig& from);

  inline DailyTaskInitDataConfig& operator=(const DailyTaskInitDataConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DailyTaskInitDataConfig& default_instance();

  void Swap(DailyTaskInitDataConfig* other);

  // implements Message ----------------------------------------------

  DailyTaskInitDataConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DailyTaskInitDataConfig& from);
  void MergeFrom(const DailyTaskInitDataConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .DianShiTech.Config.ConfigTypeGroup rate2 = 4;
  inline int rate2_size() const;
  inline void clear_rate2();
  static const int kRate2FieldNumber = 4;
  inline const ::DianShiTech::Config::ConfigTypeGroup& rate2(int index) const;
  inline ::DianShiTech::Config::ConfigTypeGroup* mutable_rate2(int index);
  inline ::DianShiTech::Config::ConfigTypeGroup* add_rate2();
  inline const ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup >&
      rate2() const;
  inline ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup >*
      mutable_rate2();

  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // repeated .DianShiTech.Config.ConfigTypeGroup rate3 = 5;
  inline int rate3_size() const;
  inline void clear_rate3();
  static const int kRate3FieldNumber = 5;
  inline const ::DianShiTech::Config::ConfigTypeGroup& rate3(int index) const;
  inline ::DianShiTech::Config::ConfigTypeGroup* mutable_rate3(int index);
  inline ::DianShiTech::Config::ConfigTypeGroup* add_rate3();
  inline const ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup >&
      rate3() const;
  inline ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup >*
      mutable_rate3();

  // repeated .DianShiTech.Config.ConfigTypeGroup rate1 = 3;
  inline int rate1_size() const;
  inline void clear_rate1();
  static const int kRate1FieldNumber = 3;
  inline const ::DianShiTech::Config::ConfigTypeGroup& rate1(int index) const;
  inline ::DianShiTech::Config::ConfigTypeGroup* mutable_rate1(int index);
  inline ::DianShiTech::Config::ConfigTypeGroup* add_rate1();
  inline const ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup >&
      rate1() const;
  inline ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup >*
      mutable_rate1();

  // optional int32 daily_refresh_count = 2;
  inline bool has_daily_refresh_count() const;
  inline void clear_daily_refresh_count();
  static const int kDailyRefreshCountFieldNumber = 2;
  inline ::google::protobuf::int32 daily_refresh_count() const;
  inline void set_daily_refresh_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:DianShiTech.Config.DailyTaskInitDataConfig)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_daily_refresh_count();
  inline void clear_has_daily_refresh_count();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup > rate2_;
  ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup > rate3_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 daily_refresh_count_;
  ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup > rate1_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_DailyTaskInitDataConfig_2eproto();
  friend void protobuf_AssignDesc_DailyTaskInitDataConfig_2eproto();
  friend void protobuf_ShutdownFile_DailyTaskInitDataConfig_2eproto();

  void InitAsDefaultInstance();
  static DailyTaskInitDataConfig* default_instance_;
};
// ===================================================================


// ===================================================================

// DailyTaskInitDataConfig

// repeated .DianShiTech.Config.ConfigTypeGroup rate2 = 4;
inline int DailyTaskInitDataConfig::rate2_size() const {
  return rate2_.size();
}
inline void DailyTaskInitDataConfig::clear_rate2() {
  rate2_.Clear();
}
inline const ::DianShiTech::Config::ConfigTypeGroup& DailyTaskInitDataConfig::rate2(int index) const {
  return rate2_.Get(index);
}
inline ::DianShiTech::Config::ConfigTypeGroup* DailyTaskInitDataConfig::mutable_rate2(int index) {
  return rate2_.Mutable(index);
}
inline ::DianShiTech::Config::ConfigTypeGroup* DailyTaskInitDataConfig::add_rate2() {
  return rate2_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup >&
DailyTaskInitDataConfig::rate2() const {
  return rate2_;
}
inline ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup >*
DailyTaskInitDataConfig::mutable_rate2() {
  return &rate2_;
}

// optional int32 id = 1;
inline bool DailyTaskInitDataConfig::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DailyTaskInitDataConfig::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DailyTaskInitDataConfig::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DailyTaskInitDataConfig::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 DailyTaskInitDataConfig::id() const {
  return id_;
}
inline void DailyTaskInitDataConfig::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// repeated .DianShiTech.Config.ConfigTypeGroup rate3 = 5;
inline int DailyTaskInitDataConfig::rate3_size() const {
  return rate3_.size();
}
inline void DailyTaskInitDataConfig::clear_rate3() {
  rate3_.Clear();
}
inline const ::DianShiTech::Config::ConfigTypeGroup& DailyTaskInitDataConfig::rate3(int index) const {
  return rate3_.Get(index);
}
inline ::DianShiTech::Config::ConfigTypeGroup* DailyTaskInitDataConfig::mutable_rate3(int index) {
  return rate3_.Mutable(index);
}
inline ::DianShiTech::Config::ConfigTypeGroup* DailyTaskInitDataConfig::add_rate3() {
  return rate3_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup >&
DailyTaskInitDataConfig::rate3() const {
  return rate3_;
}
inline ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup >*
DailyTaskInitDataConfig::mutable_rate3() {
  return &rate3_;
}

// repeated .DianShiTech.Config.ConfigTypeGroup rate1 = 3;
inline int DailyTaskInitDataConfig::rate1_size() const {
  return rate1_.size();
}
inline void DailyTaskInitDataConfig::clear_rate1() {
  rate1_.Clear();
}
inline const ::DianShiTech::Config::ConfigTypeGroup& DailyTaskInitDataConfig::rate1(int index) const {
  return rate1_.Get(index);
}
inline ::DianShiTech::Config::ConfigTypeGroup* DailyTaskInitDataConfig::mutable_rate1(int index) {
  return rate1_.Mutable(index);
}
inline ::DianShiTech::Config::ConfigTypeGroup* DailyTaskInitDataConfig::add_rate1() {
  return rate1_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup >&
DailyTaskInitDataConfig::rate1() const {
  return rate1_;
}
inline ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup >*
DailyTaskInitDataConfig::mutable_rate1() {
  return &rate1_;
}

// optional int32 daily_refresh_count = 2;
inline bool DailyTaskInitDataConfig::has_daily_refresh_count() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void DailyTaskInitDataConfig::set_has_daily_refresh_count() {
  _has_bits_[0] |= 0x00000010u;
}
inline void DailyTaskInitDataConfig::clear_has_daily_refresh_count() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void DailyTaskInitDataConfig::clear_daily_refresh_count() {
  daily_refresh_count_ = 0;
  clear_has_daily_refresh_count();
}
inline ::google::protobuf::int32 DailyTaskInitDataConfig::daily_refresh_count() const {
  return daily_refresh_count_;
}
inline void DailyTaskInitDataConfig::set_daily_refresh_count(::google::protobuf::int32 value) {
  set_has_daily_refresh_count();
  daily_refresh_count_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Config
}  // namespace DianShiTech

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_DailyTaskInitDataConfig_2eproto__INCLUDED
