// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PositionConfig.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "PositionConfig.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace DianShiTech {
namespace Config {

namespace {

const ::google::protobuf::Descriptor* PositionConfig_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PositionConfig_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_PositionConfig_2eproto() {
  protobuf_AddDesc_PositionConfig_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "PositionConfig.proto");
  GOOGLE_CHECK(file != NULL);
  PositionConfig_descriptor_ = file->message_type(0);
  static const int PositionConfig_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PositionConfig, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PositionConfig, achievement_point_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PositionConfig, position_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PositionConfig, bonus_),
  };
  PositionConfig_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PositionConfig_descriptor_,
      PositionConfig::default_instance_,
      PositionConfig_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PositionConfig, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PositionConfig, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PositionConfig));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_PositionConfig_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PositionConfig_descriptor_, &PositionConfig::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_PositionConfig_2eproto() {
  delete PositionConfig::default_instance_;
  delete PositionConfig_reflection_;
}

void protobuf_AddDesc_PositionConfig_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::DianShiTech::Config::protobuf_AddDesc_ConfigTypeGroup_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024PositionConfig.proto\022\022DianShiTech.Conf"
    "ig\032\025ConfigTypeGroup.proto\"\202\001\n\016PositionCo"
    "nfig\022\n\n\002id\030\001 \001(\005\022\031\n\021achievement_point\030\002 "
    "\001(\005\022\025\n\rposition_name\030\003 \001(\t\0222\n\005bonus\030\004 \003("
    "\0132#.DianShiTech.Config.ConfigTypeGroup", 198);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "PositionConfig.proto", &protobuf_RegisterTypes);
  PositionConfig::default_instance_ = new PositionConfig();
  PositionConfig::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_PositionConfig_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_PositionConfig_2eproto {
  StaticDescriptorInitializer_PositionConfig_2eproto() {
    protobuf_AddDesc_PositionConfig_2eproto();
  }
} static_descriptor_initializer_PositionConfig_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int PositionConfig::kIdFieldNumber;
const int PositionConfig::kAchievementPointFieldNumber;
const int PositionConfig::kPositionNameFieldNumber;
const int PositionConfig::kBonusFieldNumber;
#endif  // !_MSC_VER

PositionConfig::PositionConfig()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PositionConfig::InitAsDefaultInstance() {
}

PositionConfig::PositionConfig(const PositionConfig& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PositionConfig::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0;
  achievement_point_ = 0;
  position_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PositionConfig::~PositionConfig() {
  SharedDtor();
}

void PositionConfig::SharedDtor() {
  if (position_name_ != &::google::protobuf::internal::kEmptyString) {
    delete position_name_;
  }
  if (this != default_instance_) {
  }
}

void PositionConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PositionConfig::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PositionConfig_descriptor_;
}

const PositionConfig& PositionConfig::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_PositionConfig_2eproto();
  return *default_instance_;
}

PositionConfig* PositionConfig::default_instance_ = NULL;

PositionConfig* PositionConfig::New() const {
  return new PositionConfig;
}

void PositionConfig::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = 0;
    achievement_point_ = 0;
    if (has_position_name()) {
      if (position_name_ != &::google::protobuf::internal::kEmptyString) {
        position_name_->clear();
      }
    }
  }
  bonus_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PositionConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_achievement_point;
        break;
      }

      // optional int32 achievement_point = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_achievement_point:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &achievement_point_)));
          set_has_achievement_point();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_position_name;
        break;
      }

      // optional string position_name = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_position_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_position_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->position_name().data(), this->position_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_bonus;
        break;
      }

      // repeated .DianShiTech.Config.ConfigTypeGroup bonus = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_bonus:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_bonus()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_bonus;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PositionConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // optional int32 achievement_point = 2;
  if (has_achievement_point()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->achievement_point(), output);
  }

  // optional string position_name = 3;
  if (has_position_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->position_name().data(), this->position_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->position_name(), output);
  }

  // repeated .DianShiTech.Config.ConfigTypeGroup bonus = 4;
  for (int i = 0; i < this->bonus_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->bonus(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PositionConfig::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // optional int32 achievement_point = 2;
  if (has_achievement_point()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->achievement_point(), target);
  }

  // optional string position_name = 3;
  if (has_position_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->position_name().data(), this->position_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->position_name(), target);
  }

  // repeated .DianShiTech.Config.ConfigTypeGroup bonus = 4;
  for (int i = 0; i < this->bonus_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->bonus(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PositionConfig::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // optional int32 achievement_point = 2;
    if (has_achievement_point()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->achievement_point());
    }

    // optional string position_name = 3;
    if (has_position_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->position_name());
    }

  }
  // repeated .DianShiTech.Config.ConfigTypeGroup bonus = 4;
  total_size += 1 * this->bonus_size();
  for (int i = 0; i < this->bonus_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->bonus(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PositionConfig::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PositionConfig* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PositionConfig*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PositionConfig::MergeFrom(const PositionConfig& from) {
  GOOGLE_CHECK_NE(&from, this);
  bonus_.MergeFrom(from.bonus_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_achievement_point()) {
      set_achievement_point(from.achievement_point());
    }
    if (from.has_position_name()) {
      set_position_name(from.position_name());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PositionConfig::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PositionConfig::CopyFrom(const PositionConfig& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PositionConfig::IsInitialized() const {

  return true;
}

void PositionConfig::Swap(PositionConfig* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(achievement_point_, other->achievement_point_);
    std::swap(position_name_, other->position_name_);
    bonus_.Swap(&other->bonus_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PositionConfig::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PositionConfig_descriptor_;
  metadata.reflection = PositionConfig_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Config
}  // namespace DianShiTech

// @@protoc_insertion_point(global_scope)
