// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PropGroupConfig.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "PropGroupConfig.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace DianShiTech {
namespace Config {

namespace {

const ::google::protobuf::Descriptor* PropGroupConfig_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PropGroupConfig_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_PropGroupConfig_2eproto() {
  protobuf_AddDesc_PropGroupConfig_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "PropGroupConfig.proto");
  GOOGLE_CHECK(file != NULL);
  PropGroupConfig_descriptor_ = file->message_type(0);
  static const int PropGroupConfig_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PropGroupConfig, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PropGroupConfig, prop_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PropGroupConfig, count_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PropGroupConfig, select_type_),
  };
  PropGroupConfig_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PropGroupConfig_descriptor_,
      PropGroupConfig::default_instance_,
      PropGroupConfig_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PropGroupConfig, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PropGroupConfig, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PropGroupConfig));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_PropGroupConfig_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PropGroupConfig_descriptor_, &PropGroupConfig::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_PropGroupConfig_2eproto() {
  delete PropGroupConfig::default_instance_;
  delete PropGroupConfig_reflection_;
}

void protobuf_AddDesc_PropGroupConfig_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::DianShiTech::Config::protobuf_AddDesc_ConfigTypeGroup_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025PropGroupConfig.proto\022\022DianShiTech.Con"
    "fig\032\025ConfigTypeGroup.proto\"w\n\017PropGroupC"
    "onfig\022\n\n\002id\030\001 \001(\005\0224\n\007prop_id\030\004 \003(\0132#.Dia"
    "nShiTech.Config.ConfigTypeGroup\022\r\n\005count"
    "\030\003 \001(\005\022\023\n\013select_type\030\002 \001(\005", 187);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "PropGroupConfig.proto", &protobuf_RegisterTypes);
  PropGroupConfig::default_instance_ = new PropGroupConfig();
  PropGroupConfig::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_PropGroupConfig_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_PropGroupConfig_2eproto {
  StaticDescriptorInitializer_PropGroupConfig_2eproto() {
    protobuf_AddDesc_PropGroupConfig_2eproto();
  }
} static_descriptor_initializer_PropGroupConfig_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int PropGroupConfig::kIdFieldNumber;
const int PropGroupConfig::kPropIdFieldNumber;
const int PropGroupConfig::kCountFieldNumber;
const int PropGroupConfig::kSelectTypeFieldNumber;
#endif  // !_MSC_VER

PropGroupConfig::PropGroupConfig()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PropGroupConfig::InitAsDefaultInstance() {
}

PropGroupConfig::PropGroupConfig(const PropGroupConfig& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PropGroupConfig::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0;
  count_ = 0;
  select_type_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PropGroupConfig::~PropGroupConfig() {
  SharedDtor();
}

void PropGroupConfig::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PropGroupConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PropGroupConfig::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PropGroupConfig_descriptor_;
}

const PropGroupConfig& PropGroupConfig::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_PropGroupConfig_2eproto();
  return *default_instance_;
}

PropGroupConfig* PropGroupConfig::default_instance_ = NULL;

PropGroupConfig* PropGroupConfig::New() const {
  return new PropGroupConfig;
}

void PropGroupConfig::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = 0;
    count_ = 0;
    select_type_ = 0;
  }
  prop_id_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PropGroupConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_select_type;
        break;
      }

      // optional int32 select_type = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_select_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &select_type_)));
          set_has_select_type();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_count;
        break;
      }

      // optional int32 count = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_count:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &count_)));
          set_has_count();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_prop_id;
        break;
      }

      // repeated .DianShiTech.Config.ConfigTypeGroup prop_id = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_prop_id:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_prop_id()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_prop_id;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PropGroupConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // optional int32 select_type = 2;
  if (has_select_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->select_type(), output);
  }

  // optional int32 count = 3;
  if (has_count()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->count(), output);
  }

  // repeated .DianShiTech.Config.ConfigTypeGroup prop_id = 4;
  for (int i = 0; i < this->prop_id_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->prop_id(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PropGroupConfig::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // optional int32 select_type = 2;
  if (has_select_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->select_type(), target);
  }

  // optional int32 count = 3;
  if (has_count()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->count(), target);
  }

  // repeated .DianShiTech.Config.ConfigTypeGroup prop_id = 4;
  for (int i = 0; i < this->prop_id_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->prop_id(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PropGroupConfig::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // optional int32 count = 3;
    if (has_count()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->count());
    }

    // optional int32 select_type = 2;
    if (has_select_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->select_type());
    }

  }
  // repeated .DianShiTech.Config.ConfigTypeGroup prop_id = 4;
  total_size += 1 * this->prop_id_size();
  for (int i = 0; i < this->prop_id_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->prop_id(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PropGroupConfig::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PropGroupConfig* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PropGroupConfig*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PropGroupConfig::MergeFrom(const PropGroupConfig& from) {
  GOOGLE_CHECK_NE(&from, this);
  prop_id_.MergeFrom(from.prop_id_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_count()) {
      set_count(from.count());
    }
    if (from.has_select_type()) {
      set_select_type(from.select_type());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PropGroupConfig::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PropGroupConfig::CopyFrom(const PropGroupConfig& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PropGroupConfig::IsInitialized() const {

  return true;
}

void PropGroupConfig::Swap(PropGroupConfig* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    prop_id_.Swap(&other->prop_id_);
    std::swap(count_, other->count_);
    std::swap(select_type_, other->select_type_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PropGroupConfig::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PropGroupConfig_descriptor_;
  metadata.reflection = PropGroupConfig_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Config
}  // namespace DianShiTech

// @@protoc_insertion_point(global_scope)
