// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Stage_GuideConfig.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Stage_GuideConfig.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace DianShiTech {
namespace Config {

namespace {

const ::google::protobuf::Descriptor* Stage_GuideConfig_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Stage_GuideConfig_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_Stage_5fGuideConfig_2eproto() {
  protobuf_AddDesc_Stage_5fGuideConfig_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Stage_GuideConfig.proto");
  GOOGLE_CHECK(file != NULL);
  Stage_GuideConfig_descriptor_ = file->message_type(0);
  static const int Stage_GuideConfig_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stage_GuideConfig, open_task_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stage_GuideConfig, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stage_GuideConfig, close_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stage_GuideConfig, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stage_GuideConfig, stepid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stage_GuideConfig, type_value_),
  };
  Stage_GuideConfig_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Stage_GuideConfig_descriptor_,
      Stage_GuideConfig::default_instance_,
      Stage_GuideConfig_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stage_GuideConfig, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Stage_GuideConfig, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Stage_GuideConfig));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Stage_5fGuideConfig_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Stage_GuideConfig_descriptor_, &Stage_GuideConfig::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Stage_5fGuideConfig_2eproto() {
  delete Stage_GuideConfig::default_instance_;
  delete Stage_GuideConfig_reflection_;
}

void protobuf_AddDesc_Stage_5fGuideConfig_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::DianShiTech::Config::protobuf_AddDesc_ConfigTypeGroup_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027Stage_GuideConfig.proto\022\022DianShiTech.C"
    "onfig\032\025ConfigTypeGroup.proto\"s\n\021Stage_Gu"
    "ideConfig\022\021\n\topen_task\030\005 \001(\005\022\014\n\004type\030\003 \001"
    "(\005\022\r\n\005close\030\006 \001(\005\022\n\n\002id\030\001 \001(\005\022\016\n\006stepid\030"
    "\002 \003(\005\022\022\n\ntype_value\030\004 \001(\005", 185);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Stage_GuideConfig.proto", &protobuf_RegisterTypes);
  Stage_GuideConfig::default_instance_ = new Stage_GuideConfig();
  Stage_GuideConfig::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Stage_5fGuideConfig_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Stage_5fGuideConfig_2eproto {
  StaticDescriptorInitializer_Stage_5fGuideConfig_2eproto() {
    protobuf_AddDesc_Stage_5fGuideConfig_2eproto();
  }
} static_descriptor_initializer_Stage_5fGuideConfig_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Stage_GuideConfig::kOpenTaskFieldNumber;
const int Stage_GuideConfig::kTypeFieldNumber;
const int Stage_GuideConfig::kCloseFieldNumber;
const int Stage_GuideConfig::kIdFieldNumber;
const int Stage_GuideConfig::kStepidFieldNumber;
const int Stage_GuideConfig::kTypeValueFieldNumber;
#endif  // !_MSC_VER

Stage_GuideConfig::Stage_GuideConfig()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Stage_GuideConfig::InitAsDefaultInstance() {
}

Stage_GuideConfig::Stage_GuideConfig(const Stage_GuideConfig& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Stage_GuideConfig::SharedCtor() {
  _cached_size_ = 0;
  open_task_ = 0;
  type_ = 0;
  close_ = 0;
  id_ = 0;
  type_value_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Stage_GuideConfig::~Stage_GuideConfig() {
  SharedDtor();
}

void Stage_GuideConfig::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Stage_GuideConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Stage_GuideConfig::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Stage_GuideConfig_descriptor_;
}

const Stage_GuideConfig& Stage_GuideConfig::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Stage_5fGuideConfig_2eproto();
  return *default_instance_;
}

Stage_GuideConfig* Stage_GuideConfig::default_instance_ = NULL;

Stage_GuideConfig* Stage_GuideConfig::New() const {
  return new Stage_GuideConfig;
}

void Stage_GuideConfig::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    open_task_ = 0;
    type_ = 0;
    close_ = 0;
    id_ = 0;
    type_value_ = 0;
  }
  stepid_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Stage_GuideConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_stepid;
        break;
      }

      // repeated int32 stepid = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_stepid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 16, input, this->mutable_stepid())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_stepid())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_stepid;
        if (input->ExpectTag(24)) goto parse_type;
        break;
      }

      // optional int32 type = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_)));
          set_has_type();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_type_value;
        break;
      }

      // optional int32 type_value = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_type_value:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_value_)));
          set_has_type_value();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_open_task;
        break;
      }

      // optional int32 open_task = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_open_task:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &open_task_)));
          set_has_open_task();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_close;
        break;
      }

      // optional int32 close = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_close:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &close_)));
          set_has_close();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Stage_GuideConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // repeated int32 stepid = 2;
  for (int i = 0; i < this->stepid_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      2, this->stepid(i), output);
  }

  // optional int32 type = 3;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->type(), output);
  }

  // optional int32 type_value = 4;
  if (has_type_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->type_value(), output);
  }

  // optional int32 open_task = 5;
  if (has_open_task()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->open_task(), output);
  }

  // optional int32 close = 6;
  if (has_close()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->close(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Stage_GuideConfig::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // repeated int32 stepid = 2;
  for (int i = 0; i < this->stepid_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(2, this->stepid(i), target);
  }

  // optional int32 type = 3;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->type(), target);
  }

  // optional int32 type_value = 4;
  if (has_type_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->type_value(), target);
  }

  // optional int32 open_task = 5;
  if (has_open_task()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->open_task(), target);
  }

  // optional int32 close = 6;
  if (has_close()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->close(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Stage_GuideConfig::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 open_task = 5;
    if (has_open_task()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->open_task());
    }

    // optional int32 type = 3;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->type());
    }

    // optional int32 close = 6;
    if (has_close()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->close());
    }

    // optional int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // optional int32 type_value = 4;
    if (has_type_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->type_value());
    }

  }
  // repeated int32 stepid = 2;
  {
    int data_size = 0;
    for (int i = 0; i < this->stepid_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->stepid(i));
    }
    total_size += 1 * this->stepid_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Stage_GuideConfig::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Stage_GuideConfig* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Stage_GuideConfig*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Stage_GuideConfig::MergeFrom(const Stage_GuideConfig& from) {
  GOOGLE_CHECK_NE(&from, this);
  stepid_.MergeFrom(from.stepid_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_open_task()) {
      set_open_task(from.open_task());
    }
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_close()) {
      set_close(from.close());
    }
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_type_value()) {
      set_type_value(from.type_value());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Stage_GuideConfig::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Stage_GuideConfig::CopyFrom(const Stage_GuideConfig& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Stage_GuideConfig::IsInitialized() const {

  return true;
}

void Stage_GuideConfig::Swap(Stage_GuideConfig* other) {
  if (other != this) {
    std::swap(open_task_, other->open_task_);
    std::swap(type_, other->type_);
    std::swap(close_, other->close_);
    std::swap(id_, other->id_);
    stepid_.Swap(&other->stepid_);
    std::swap(type_value_, other->type_value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Stage_GuideConfig::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Stage_GuideConfig_descriptor_;
  metadata.reflection = Stage_GuideConfig_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Config
}  // namespace DianShiTech

// @@protoc_insertion_point(global_scope)
