// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Talent_initial_idConfig.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Talent_initial_idConfig.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace DianShiTech {
namespace Config {

namespace {

const ::google::protobuf::Descriptor* Talent_initial_idConfig_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Talent_initial_idConfig_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_Talent_5finitial_5fidConfig_2eproto() {
  protobuf_AddDesc_Talent_5finitial_5fidConfig_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Talent_initial_idConfig.proto");
  GOOGLE_CHECK(file != NULL);
  Talent_initial_idConfig_descriptor_ = file->message_type(0);
  static const int Talent_initial_idConfig_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Talent_initial_idConfig, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Talent_initial_idConfig, start_id_),
  };
  Talent_initial_idConfig_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Talent_initial_idConfig_descriptor_,
      Talent_initial_idConfig::default_instance_,
      Talent_initial_idConfig_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Talent_initial_idConfig, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Talent_initial_idConfig, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Talent_initial_idConfig));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Talent_5finitial_5fidConfig_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Talent_initial_idConfig_descriptor_, &Talent_initial_idConfig::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Talent_5finitial_5fidConfig_2eproto() {
  delete Talent_initial_idConfig::default_instance_;
  delete Talent_initial_idConfig_reflection_;
}

void protobuf_AddDesc_Talent_5finitial_5fidConfig_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::DianShiTech::Config::protobuf_AddDesc_ConfigTypeGroup_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\035Talent_initial_idConfig.proto\022\022DianShi"
    "Tech.Config\032\025ConfigTypeGroup.proto\"7\n\027Ta"
    "lent_initial_idConfig\022\n\n\002id\030\001 \001(\005\022\020\n\010sta"
    "rt_id\030\002 \001(\005", 131);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Talent_initial_idConfig.proto", &protobuf_RegisterTypes);
  Talent_initial_idConfig::default_instance_ = new Talent_initial_idConfig();
  Talent_initial_idConfig::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Talent_5finitial_5fidConfig_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Talent_5finitial_5fidConfig_2eproto {
  StaticDescriptorInitializer_Talent_5finitial_5fidConfig_2eproto() {
    protobuf_AddDesc_Talent_5finitial_5fidConfig_2eproto();
  }
} static_descriptor_initializer_Talent_5finitial_5fidConfig_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Talent_initial_idConfig::kIdFieldNumber;
const int Talent_initial_idConfig::kStartIdFieldNumber;
#endif  // !_MSC_VER

Talent_initial_idConfig::Talent_initial_idConfig()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Talent_initial_idConfig::InitAsDefaultInstance() {
}

Talent_initial_idConfig::Talent_initial_idConfig(const Talent_initial_idConfig& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Talent_initial_idConfig::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0;
  start_id_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Talent_initial_idConfig::~Talent_initial_idConfig() {
  SharedDtor();
}

void Talent_initial_idConfig::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Talent_initial_idConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Talent_initial_idConfig::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Talent_initial_idConfig_descriptor_;
}

const Talent_initial_idConfig& Talent_initial_idConfig::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Talent_5finitial_5fidConfig_2eproto();
  return *default_instance_;
}

Talent_initial_idConfig* Talent_initial_idConfig::default_instance_ = NULL;

Talent_initial_idConfig* Talent_initial_idConfig::New() const {
  return new Talent_initial_idConfig;
}

void Talent_initial_idConfig::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = 0;
    start_id_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Talent_initial_idConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_start_id;
        break;
      }

      // optional int32 start_id = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_start_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &start_id_)));
          set_has_start_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Talent_initial_idConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // optional int32 start_id = 2;
  if (has_start_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->start_id(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Talent_initial_idConfig::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // optional int32 start_id = 2;
  if (has_start_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->start_id(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Talent_initial_idConfig::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // optional int32 start_id = 2;
    if (has_start_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->start_id());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Talent_initial_idConfig::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Talent_initial_idConfig* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Talent_initial_idConfig*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Talent_initial_idConfig::MergeFrom(const Talent_initial_idConfig& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_start_id()) {
      set_start_id(from.start_id());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Talent_initial_idConfig::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Talent_initial_idConfig::CopyFrom(const Talent_initial_idConfig& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Talent_initial_idConfig::IsInitialized() const {

  return true;
}

void Talent_initial_idConfig::Swap(Talent_initial_idConfig* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(start_id_, other->start_id_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Talent_initial_idConfig::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Talent_initial_idConfig_descriptor_;
  metadata.reflection = Talent_initial_idConfig_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Config
}  // namespace DianShiTech

// @@protoc_insertion_point(global_scope)
