// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TotalDamageBonusConfig.proto

#ifndef PROTOBUF_TotalDamageBonusConfig_2eproto__INCLUDED
#define PROTOBUF_TotalDamageBonusConfig_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "ConfigTypeGroup.pb.h"
// @@protoc_insertion_point(includes)

namespace DianShiTech {
namespace Config {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_TotalDamageBonusConfig_2eproto();
void protobuf_AssignDesc_TotalDamageBonusConfig_2eproto();
void protobuf_ShutdownFile_TotalDamageBonusConfig_2eproto();

class TotalDamageBonusConfig;

// ===================================================================

class TotalDamageBonusConfig : public ::google::protobuf::Message {
 public:
  TotalDamageBonusConfig();
  virtual ~TotalDamageBonusConfig();

  TotalDamageBonusConfig(const TotalDamageBonusConfig& from);

  inline TotalDamageBonusConfig& operator=(const TotalDamageBonusConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TotalDamageBonusConfig& default_instance();

  void Swap(TotalDamageBonusConfig* other);

  // implements Message ----------------------------------------------

  TotalDamageBonusConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TotalDamageBonusConfig& from);
  void MergeFrom(const TotalDamageBonusConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // optional int32 max_rank = 3;
  inline bool has_max_rank() const;
  inline void clear_max_rank();
  static const int kMaxRankFieldNumber = 3;
  inline ::google::protobuf::int32 max_rank() const;
  inline void set_max_rank(::google::protobuf::int32 value);

  // optional int32 min_rank = 2;
  inline bool has_min_rank() const;
  inline void clear_min_rank();
  static const int kMinRankFieldNumber = 2;
  inline ::google::protobuf::int32 min_rank() const;
  inline void set_min_rank(::google::protobuf::int32 value);

  // repeated .DianShiTech.Config.ConfigTypeGroup bonus = 4;
  inline int bonus_size() const;
  inline void clear_bonus();
  static const int kBonusFieldNumber = 4;
  inline const ::DianShiTech::Config::ConfigTypeGroup& bonus(int index) const;
  inline ::DianShiTech::Config::ConfigTypeGroup* mutable_bonus(int index);
  inline ::DianShiTech::Config::ConfigTypeGroup* add_bonus();
  inline const ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup >&
      bonus() const;
  inline ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup >*
      mutable_bonus();

  // @@protoc_insertion_point(class_scope:DianShiTech.Config.TotalDamageBonusConfig)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_max_rank();
  inline void clear_has_max_rank();
  inline void set_has_min_rank();
  inline void clear_has_min_rank();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 max_rank_;
  ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup > bonus_;
  ::google::protobuf::int32 min_rank_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_TotalDamageBonusConfig_2eproto();
  friend void protobuf_AssignDesc_TotalDamageBonusConfig_2eproto();
  friend void protobuf_ShutdownFile_TotalDamageBonusConfig_2eproto();

  void InitAsDefaultInstance();
  static TotalDamageBonusConfig* default_instance_;
};
// ===================================================================


// ===================================================================

// TotalDamageBonusConfig

// optional int32 id = 1;
inline bool TotalDamageBonusConfig::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TotalDamageBonusConfig::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TotalDamageBonusConfig::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TotalDamageBonusConfig::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 TotalDamageBonusConfig::id() const {
  return id_;
}
inline void TotalDamageBonusConfig::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// optional int32 max_rank = 3;
inline bool TotalDamageBonusConfig::has_max_rank() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TotalDamageBonusConfig::set_has_max_rank() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TotalDamageBonusConfig::clear_has_max_rank() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TotalDamageBonusConfig::clear_max_rank() {
  max_rank_ = 0;
  clear_has_max_rank();
}
inline ::google::protobuf::int32 TotalDamageBonusConfig::max_rank() const {
  return max_rank_;
}
inline void TotalDamageBonusConfig::set_max_rank(::google::protobuf::int32 value) {
  set_has_max_rank();
  max_rank_ = value;
}

// optional int32 min_rank = 2;
inline bool TotalDamageBonusConfig::has_min_rank() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TotalDamageBonusConfig::set_has_min_rank() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TotalDamageBonusConfig::clear_has_min_rank() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TotalDamageBonusConfig::clear_min_rank() {
  min_rank_ = 0;
  clear_has_min_rank();
}
inline ::google::protobuf::int32 TotalDamageBonusConfig::min_rank() const {
  return min_rank_;
}
inline void TotalDamageBonusConfig::set_min_rank(::google::protobuf::int32 value) {
  set_has_min_rank();
  min_rank_ = value;
}

// repeated .DianShiTech.Config.ConfigTypeGroup bonus = 4;
inline int TotalDamageBonusConfig::bonus_size() const {
  return bonus_.size();
}
inline void TotalDamageBonusConfig::clear_bonus() {
  bonus_.Clear();
}
inline const ::DianShiTech::Config::ConfigTypeGroup& TotalDamageBonusConfig::bonus(int index) const {
  return bonus_.Get(index);
}
inline ::DianShiTech::Config::ConfigTypeGroup* TotalDamageBonusConfig::mutable_bonus(int index) {
  return bonus_.Mutable(index);
}
inline ::DianShiTech::Config::ConfigTypeGroup* TotalDamageBonusConfig::add_bonus() {
  return bonus_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup >&
TotalDamageBonusConfig::bonus() const {
  return bonus_;
}
inline ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup >*
TotalDamageBonusConfig::mutable_bonus() {
  return &bonus_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Config
}  // namespace DianShiTech

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_TotalDamageBonusConfig_2eproto__INCLUDED
