// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: XilianConfig.proto

#ifndef PROTOBUF_XilianConfig_2eproto__INCLUDED
#define PROTOBUF_XilianConfig_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "ConfigTypeGroup.pb.h"
// @@protoc_insertion_point(includes)

namespace DianShiTech {
namespace Config {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_XilianConfig_2eproto();
void protobuf_AssignDesc_XilianConfig_2eproto();
void protobuf_ShutdownFile_XilianConfig_2eproto();

class XilianConfig;

// ===================================================================

class XilianConfig : public ::google::protobuf::Message {
 public:
  XilianConfig();
  virtual ~XilianConfig();

  XilianConfig(const XilianConfig& from);

  inline XilianConfig& operator=(const XilianConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const XilianConfig& default_instance();

  void Swap(XilianConfig* other);

  // implements Message ----------------------------------------------

  XilianConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const XilianConfig& from);
  void MergeFrom(const XilianConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 equip_rank = 2;
  inline bool has_equip_rank() const;
  inline void clear_equip_rank();
  static const int kEquipRankFieldNumber = 2;
  inline ::google::protobuf::int32 equip_rank() const;
  inline void set_equip_rank(::google::protobuf::int32 value);

  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // repeated .DianShiTech.Config.ConfigTypeGroup consume = 5;
  inline int consume_size() const;
  inline void clear_consume();
  static const int kConsumeFieldNumber = 5;
  inline const ::DianShiTech::Config::ConfigTypeGroup& consume(int index) const;
  inline ::DianShiTech::Config::ConfigTypeGroup* mutable_consume(int index);
  inline ::DianShiTech::Config::ConfigTypeGroup* add_consume();
  inline const ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup >&
      consume() const;
  inline ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup >*
      mutable_consume();

  // optional int32 lock_count = 4;
  inline bool has_lock_count() const;
  inline void clear_lock_count();
  static const int kLockCountFieldNumber = 4;
  inline ::google::protobuf::int32 lock_count() const;
  inline void set_lock_count(::google::protobuf::int32 value);

  // optional int32 quality = 3;
  inline bool has_quality() const;
  inline void clear_quality();
  static const int kQualityFieldNumber = 3;
  inline ::google::protobuf::int32 quality() const;
  inline void set_quality(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:DianShiTech.Config.XilianConfig)
 private:
  inline void set_has_equip_rank();
  inline void clear_has_equip_rank();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_lock_count();
  inline void clear_has_lock_count();
  inline void set_has_quality();
  inline void clear_has_quality();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 equip_rank_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup > consume_;
  ::google::protobuf::int32 lock_count_;
  ::google::protobuf::int32 quality_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_XilianConfig_2eproto();
  friend void protobuf_AssignDesc_XilianConfig_2eproto();
  friend void protobuf_ShutdownFile_XilianConfig_2eproto();

  void InitAsDefaultInstance();
  static XilianConfig* default_instance_;
};
// ===================================================================


// ===================================================================

// XilianConfig

// optional int32 equip_rank = 2;
inline bool XilianConfig::has_equip_rank() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void XilianConfig::set_has_equip_rank() {
  _has_bits_[0] |= 0x00000001u;
}
inline void XilianConfig::clear_has_equip_rank() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void XilianConfig::clear_equip_rank() {
  equip_rank_ = 0;
  clear_has_equip_rank();
}
inline ::google::protobuf::int32 XilianConfig::equip_rank() const {
  return equip_rank_;
}
inline void XilianConfig::set_equip_rank(::google::protobuf::int32 value) {
  set_has_equip_rank();
  equip_rank_ = value;
}

// optional int32 id = 1;
inline bool XilianConfig::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void XilianConfig::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void XilianConfig::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void XilianConfig::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 XilianConfig::id() const {
  return id_;
}
inline void XilianConfig::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// repeated .DianShiTech.Config.ConfigTypeGroup consume = 5;
inline int XilianConfig::consume_size() const {
  return consume_.size();
}
inline void XilianConfig::clear_consume() {
  consume_.Clear();
}
inline const ::DianShiTech::Config::ConfigTypeGroup& XilianConfig::consume(int index) const {
  return consume_.Get(index);
}
inline ::DianShiTech::Config::ConfigTypeGroup* XilianConfig::mutable_consume(int index) {
  return consume_.Mutable(index);
}
inline ::DianShiTech::Config::ConfigTypeGroup* XilianConfig::add_consume() {
  return consume_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup >&
XilianConfig::consume() const {
  return consume_;
}
inline ::google::protobuf::RepeatedPtrField< ::DianShiTech::Config::ConfigTypeGroup >*
XilianConfig::mutable_consume() {
  return &consume_;
}

// optional int32 lock_count = 4;
inline bool XilianConfig::has_lock_count() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void XilianConfig::set_has_lock_count() {
  _has_bits_[0] |= 0x00000008u;
}
inline void XilianConfig::clear_has_lock_count() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void XilianConfig::clear_lock_count() {
  lock_count_ = 0;
  clear_has_lock_count();
}
inline ::google::protobuf::int32 XilianConfig::lock_count() const {
  return lock_count_;
}
inline void XilianConfig::set_lock_count(::google::protobuf::int32 value) {
  set_has_lock_count();
  lock_count_ = value;
}

// optional int32 quality = 3;
inline bool XilianConfig::has_quality() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void XilianConfig::set_has_quality() {
  _has_bits_[0] |= 0x00000010u;
}
inline void XilianConfig::clear_has_quality() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void XilianConfig::clear_quality() {
  quality_ = 0;
  clear_has_quality();
}
inline ::google::protobuf::int32 XilianConfig::quality() const {
  return quality_;
}
inline void XilianConfig::set_quality(::google::protobuf::int32 value) {
  set_has_quality();
  quality_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Config
}  // namespace DianShiTech

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_XilianConfig_2eproto__INCLUDED
